kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "InPlacePodVerticalScaling": true
  "PodObservedGenerationTracking": true
networking:
  ipFamily: ipv4
nodes:
- role: control-plane
- role: worker
- role: worker
